image: node:14

stages:
  - test

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'
  YARN_CACHE_FOLDER: '/root/.cache/yarn'

cache:
  paths:
    - /root/.cache/
    - cache/Cypress
    - $CI_PROJECT_DIR/node_modules/
  key: ${CI_COMMIT_REF_SLUG}

test:
  stage: test
  image:
    name: cypress/included:8.7.0
    entrypoint: ['']
  script:
    # Uncomment for debugging
    # - export
    - yarn cache dir
    - cd -- "$CI_PROJECT_DIR"
    - yarn --frozen-lockfile
    - yarn test:ci-components
    - yarn start
    - yarn test:ci
  coverage: '/Lines\s+:\s(\d+.?\d+)%/'
  artifacts:
    paths:
      - '$CI_PROJECT_DIR/tests/e2e/videos/*.mp4'
      - '$CI_PROJECT_DIR/coverage'
    expire_in: 2 weeks
    when: on_failure
  timeout: 15m
